import React, { useState } from 'react';
import { Modal, Input, Button, Descriptions, Tag, Typography, message, Divider } from 'antd';
import { FileTextOutlined, CopyOutlined, CheckCircleOutlined, SendOutlined, ThunderboltOutlined } from '@ant-design/icons';
import { useStore, Patient } from '../store/useStore';
import { aiPost } from '../lib/aiClient';

const { Text } = Typography;
const { TextArea } = Input;

interface ReferralModalProps {
  open: boolean;
  onClose: () => void;
  patient: Patient | null;
}

interface AIReferralData {
  header: {
    date: string;
    from: string;
    to: string;
    re: string;
  };
  body: {
    introduction: string;
    clinicalSummary: string;
    currentVitals: string;
    additionalNotes: string;
    closing: string;
  };
  urgency: string;
  mock: boolean;
}

export function ReferralModal({ open, onClose, patient }: ReferralModalProps) {
  const { doctorProfile, hospitals, activeHospitalId, addAuditEntry, settings } = useStore();
  const [referralNotes, setReferralNotes] = useState('');
  const [copied, setCopied] = useState(false);
  const [aiReferral, setAiReferral] = useState<AIReferralData | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);

  const activeHospital = hospitals.find((h) => h.id === activeHospitalId);

  if (!patient) return null;

  const vitalsSummary = [
    `HR: ${patient.vitals.heartRate.value} ${patient.vitals.heartRate.unit}`,
    `BP: ${patient.vitals.bloodPressure.sys}/${patient.vitals.bloodPressure.dia} mmHg`,
    `SpO2: ${patient.vitals.spO2.value}%`,
    `Temp: ${patient.vitals.temperature.value}${patient.vitals.temperature.unit}`,
    `RR: ${patient.vitals.respiration.value}${patient.vitals.respiration.unit}`,
  ].join(' | ');

  const handleGenerateAI = async () => {
    setIsGenerating(true);
    try {
      const result = await aiPost<AIReferralData>('/api/generate-referral', {
        patient: {
          name: patient.name,
          age: patient.age,
          gender: patient.gender,
          condition: patient.condition,
          vitals: {
            heartRate: patient.vitals.heartRate.value,
            spO2: patient.vitals.spO2.value,
            temperature: patient.vitals.temperature.value,
            respiration: patient.vitals.respiration.value,
          },
        },
        referringDoctor: doctorProfile.name,
        targetSpecialty: doctorProfile.specialization,
        reason: `Patient presenting with ${patient.condition}, risk level: ${patient.riskLevel}`,
        notes: referralNotes || undefined,
      }, settings.offlineMode);

      setAiReferral(result.data);
      message.success('AI referral generated successfully');
    } catch (err: any) {
      console.error('Referral generation error:', err);
      message.error(err.message || 'Failed to generate referral. Is the backend running?');
    } finally {
      setIsGenerating(false);
    }
  };

  // Build the referral text — use AI-generated content if available, otherwise static
  const buildReferralText = () => {
    if (aiReferral) {
      return [
        `══════════════════════════════════════════`,
        `       PATIENT REFERRAL SUMMARY`,
        `       ${activeHospital?.name || 'UrbanCare Medical Center'}`,
        `══════════════════════════════════════════`,
        ``,
        `Date: ${aiReferral.header.date}`,
        `From: ${aiReferral.header.from}`,
        `To: ${aiReferral.header.to}`,
        `Re: ${aiReferral.header.re}`,
        `Urgency: ${aiReferral.urgency.toUpperCase()}`,
        ``,
        `── INTRODUCTION ─────────────────────────`,
        aiReferral.body.introduction,
        ``,
        `── CLINICAL SUMMARY ─────────────────────`,
        aiReferral.body.clinicalSummary,
        ``,
        `── CURRENT VITALS ───────────────────────`,
        aiReferral.body.currentVitals,
        ``,
        `── ADDITIONAL NOTES ─────────────────────`,
        aiReferral.body.additionalNotes,
        ``,
        `── CLOSING ──────────────────────────────`,
        aiReferral.body.closing,
        ``,
        `══════════════════════════════════════════`,
        `Generated by UrbanCare AI Clinical Engine`,
        `Model: TxGemma${aiReferral.mock ? ' (Mock)' : ''}`,
        `══════════════════════════════════════════`,
      ].join('\n');
    }

    // Static fallback
    return [
      `══════════════════════════════════════════`,
      `       PATIENT REFERRAL SUMMARY`,
      `       ${activeHospital?.name || 'UrbanCare Medical Center'}`,
      `══════════════════════════════════════════`,
      ``,
      `Date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
      `Referral ID: REF-${Date.now().toString(36).toUpperCase()}`,
      ``,
      `── PATIENT INFORMATION ──────────────────`,
      `Name:       ${patient.name}`,
      `Patient ID: ${patient.id}`,
      `Age/Sex:    ${patient.age} years / ${patient.gender}`,
      `Condition:  ${patient.condition}`,
      `Risk Level: ${patient.riskLevel}`,
      ``,
      `── CURRENT VITALS ───────────────────────`,
      vitalsSummary,
      ``,
      `── REFERRING PHYSICIAN ──────────────────`,
      `Name:           ${doctorProfile.name}`,
      `Specialization: ${doctorProfile.specialization}`,
      `License:        ${doctorProfile.licenseNumber}`,
      `Hospital:       ${activeHospital?.name || 'UrbanCare Medical Center'}`,
      ``,
      `── REFERRAL NOTES ───────────────────────`,
      referralNotes || 'No additional notes provided.',
      ``,
      `── SOAP NOTES (IF AVAILABLE) ────────────`,
      patient.notes.soap || 'Not yet documented.',
      ``,
      `══════════════════════════════════════════`,
      `This referral was generated by UrbanCare AI`,
      `Clinical Dashboard. For verification, contact`,
      `${activeHospital?.support || 'support@urbancare.com'}`,
      `══════════════════════════════════════════`,
    ].join('\n');
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(buildReferralText());
    setCopied(true);
    addAuditEntry('Generate Referral', `Generated referral for ${patient.name} (${patient.id})`);
    message.success('Referral summary copied to clipboard!');
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <Modal
      title={
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <FileTextOutlined style={{ color: '#4f46e5' }} />
          <span>Generate Referral</span>
        </div>
      }
      open={open}
      onCancel={() => { onClose(); setAiReferral(null); }}
      footer={null}
      width={600}
      styles={{ body: { paddingTop: 16 } }}
    >
      {/* Patient Info */}
      <Descriptions
        column={2}
        size="small"
        bordered
        labelStyle={{ fontWeight: 600, width: 120, fontSize: 12 }}
        contentStyle={{ fontSize: 12 }}
        style={{ marginBottom: 16 }}
      >
        <Descriptions.Item label="Patient">{patient.name}</Descriptions.Item>
        <Descriptions.Item label="ID">{patient.id}</Descriptions.Item>
        <Descriptions.Item label="Age/Sex">{patient.age}y / {patient.gender}</Descriptions.Item>
        <Descriptions.Item label="Condition">
          <Tag color={
            patient.riskLevel === 'Critical' ? 'red' :
            patient.riskLevel === 'Warning' ? 'orange' : 'green'
          }>
            {patient.condition}
          </Tag>
        </Descriptions.Item>
      </Descriptions>

      {/* Vitals summary */}
      <div
        style={{
          background: '#f0f9ff',
          border: '1px solid #bae6fd',
          borderRadius: 10,
          padding: 12,
          marginBottom: 16,
          fontSize: 12,
          color: '#0369a1',
          fontFamily: 'monospace',
        }}
      >
        <strong>Current Vitals:</strong> {vitalsSummary}
      </div>

      {/* Referring doctor */}
      <Descriptions
        column={2}
        size="small"
        labelStyle={{ fontWeight: 600, width: 120, fontSize: 12 }}
        contentStyle={{ fontSize: 12 }}
        style={{ marginBottom: 16 }}
      >
        <Descriptions.Item label="Referring Dr.">{doctorProfile.name}</Descriptions.Item>
        <Descriptions.Item label="Specialty">{doctorProfile.specialization}</Descriptions.Item>
        <Descriptions.Item label="Hospital">{activeHospital?.name}</Descriptions.Item>
        <Descriptions.Item label="License">{doctorProfile.licenseNumber}</Descriptions.Item>
      </Descriptions>

      {/* Referral notes */}
      <Text strong style={{ fontSize: 13, display: 'block', marginBottom: 8 }}>
        Referral Notes
      </Text>
      <TextArea
        rows={3}
        placeholder="Add clinical notes, reason for referral, recommended follow-up..."
        value={referralNotes}
        onChange={(e) => setReferralNotes(e.target.value)}
        style={{ borderRadius: 10, marginBottom: 16 }}
      />

      {/* AI-generated referral preview */}
      {aiReferral && (
        <div
          style={{
            background: '#f0fdf4',
            border: '1px solid #bbf7d0',
            borderRadius: 10,
            padding: 12,
            marginBottom: 16,
            fontSize: 11,
            fontFamily: 'monospace',
            maxHeight: 160,
            overflowY: 'auto',
            whiteSpace: 'pre-wrap',
            color: '#166534',
          }}
        >
          <div style={{ marginBottom: 4, fontWeight: 600, fontSize: 12 }}>
            ✓ AI Referral Generated — {aiReferral.urgency.toUpperCase()} priority
            {aiReferral.mock && <span style={{ fontWeight: 400, color: '#6b7280' }}> (Mock — TxGemma pending)</span>}
          </div>
          {aiReferral.body.introduction}
          {'\n\n'}
          {aiReferral.body.clinicalSummary}
        </div>
      )}

      <Divider style={{ margin: '12px 0' }} />

      {/* Actions */}
      <div style={{ display: 'flex', gap: 8 }}>
        <Button
          type="primary"
          icon={copied ? <CheckCircleOutlined /> : <CopyOutlined />}
          onClick={handleCopy}
          size="large"
          block
          style={{
            borderRadius: 10,
            height: 44,
            fontWeight: 600,
            background: copied ? '#10b981' : 'linear-gradient(135deg, #4f46e5, #6366f1)',
            border: 'none',
          }}
        >
          {copied ? 'Copied!' : 'Copy Referral Summary'}
        </Button>
        <Button
          icon={<ThunderboltOutlined />}
          size="large"
          loading={isGenerating}
          onClick={handleGenerateAI}
          style={{
            borderRadius: 10,
            height: 44,
            fontWeight: 600,
            borderColor: '#4f46e5',
            color: '#4f46e5',
          }}
        >
          {isGenerating ? 'Generating…' : 'AI Generate'}
        </Button>
        <Button
          icon={<SendOutlined />}
          size="large"
          style={{ borderRadius: 10, height: 44 }}
          onClick={() => message.info('Email sending is available in production mode')}
        >
          Email
        </Button>
      </div>
    </Modal>
  );
}
